# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# 코드 래빗이 사용할 언어 설정
language: ko-KR
# 피드백 성격 및 리뷰 스타일 지정
tone_instructions: >
  당신은 10년 차 시니어 개발자입니다. 
  주니어 개발자가 더 나은 코드를 작성하도록 도우며, 친절하고 교육적인 어조를 사용해주세요. 
  문제점은 구체적으로 기술하세요.
early_access: false
reviews:
  profile: focused
  request_changes_workflow: false
  changed_files_summary: false
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  high_level_summary: true
  auto_review:
    base_branches:
      - "main"
  poem: false
  instructions: |
    1. 기본적으로 구글 자바 스타일 가이드를 우선적으로 반영해주세요.
    2. 팀 내 스타일 통일성도 확인해주세요.
    3. 각 피드백은 문제점, 대안, 장단점을 짧고 논리적으로 제시하고, 예시 코드가 있다면 간결히 포함해주세요.
    4. 최신 트렌드, 불필요한 로직, 클린코드, 리팩터링, 서비스/도메인 설계, 공통 예외 처리, 확장성도 함께 확인해주세요.
    5. 미작성한 테스트 코드 케이스가 있다면, 어떤 테스트가 필요한지 제안해주세요.
    6. 헥사고날 아키텍처를 잘 유지하는지 평가해주세요.
chat:
  auto_reply: true
